# Generated by Django 2.2 on 2021-03-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='learn_times',
            field=models.CharField(default=0, max_length=50, verbose_name='学习时长（分钟数）'),
        ),
    ]
