# Generated by Django 2.2 on 2021-03-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210316_2003'),
        ('courses', '0002_auto_20210310_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='机构'),
        ),
    ]
